services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=electronic_mail_post'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'

    ports:
      - '5436:5432'

#  sonarqube:
#    image: sonarqube:9.9-community
#    restart: always
#    container_name: sonarqube
#    depends_on:
#      - postgres
#    ports:
#      - "9000:9000"
#    networks:
#      - tools
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#    volumes:
#      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
#      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
#      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
#      - ./sonarqube/sonarqube_temp:/opt/sonarqube/temp